
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>GivlsWeapons</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\Textures\noiseTexture.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Textures\noiseTexture3.png" />
  </ItemGroup>
</Project>